steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flashdrive-311519/flashdrive:$SHORT_SHA', '.']

- name: 'docker/compose:1.29.0'
  args: ['up', '-d']

images: ['gcr.io/flashdrive-311519/flashdrive:$SHORT_SHA']