# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  backend:
    # Configuration for building the docker image for the backend service
    build:
      build: ./backend
      image: gcr.io/flashdrive/flashdrive_backend:latest
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

#  Frontend Service 
  frontend:
    build: ./frontend
    image: gcr.io/flashdrive/flashdrive_frontend:latest
    ports:
      - "5000:80" # Map the exposed port 80 on the container to port 5000 on the host machine
    restart: always
    depends_on:
      - backend
    networks:
      - frontend  

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: 