# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  backend:
    # Configuration for building the docker image for the backend service
    build:
      context: backend # Use an image built from the specified dockerfile in the `backend` directory.
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always     
    # networks: # Networks to join (Services on the same network can communicate with each other using their name)
    #   - backend
    #   - frontend
    volumes:
      - cloudsql:/cloudsql
    depends_on:
      - sql_proxy




  sql_proxy:
    environment:
      - MYSQL_ROOT_PASSWORD=fdb
      - MYSQL_DATABASE=flashdrive_db
      - MYSQL_USER=root
    image: gcr.io/cloudsql-docker/gce-proxy:1.12
    command:
      /cloud_sql_proxy
      -dir=/cloudsql
      -instances=flashdrive-311519:europe-west3:flashdrive-flashdrive_db=tcp:34.107.12.140:3306
      -credential_file=/root/keys/keyfile.json
    volumes:
      - /Users/venancekonan/Documents/STUDIUM/HAW/Semester_5/Kurse/CloudComputing/Praktikum/flashdrive/backend/src/main/resources/static/flashdrive-311519-21058c44948e.json:/root/keys/keyfile.json:ro
      - cloudsql:/cloudsql
    ports:
      - 3306:3306
           
volumes:
  # This empty property initializes a named volume.
  cloudsql:



  # Frontend Service 
  # frontend:
  #   build:
  #     context: frontend # Use an image built from the specified dockerfile in the `frontend` directory.
  #     dockerfile: Dockerfile
  #     args:
  #       REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
  #   ports:
  #     - "9090:80" # Map the exposed port 80 on the container to port 9090 on the host machine
  #   # restart: always
  #   # depends_on:
  #   #   - backend
  #   networks:
  #     - frontend  

# Networks to be created to facilitate communication between containers
networks:
  backend:
  # frontend: 