apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: flashdrivecontainerregistry2.azurecr.io/flashdrive_backend:latest
          env:
            - name: CLOUD_PROVIDER
              value: Azure
            - name: MYSQL_URL
              value: jdbc:mysql://flashdrive-mysql-server.mysql.database.azure.com:3306/flashdrive-db?useSSL=true&requireSSL=false
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: az-sql-db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: az-sql-db-credentials
                  key: password
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: az-storage-credentials
                  key: connection
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: az-storage-credentials
                  key: container
          ports:
          - containerPort: 8080