version: '3.7'

# Define services
services:
  # App backend service
  backend:
    # Configuration for building the docker image for the backend service
    build: ./../backend
    image: flashdrivecontainerregistry2.azurecr.io/flashdrive_backend
    restart: always     

#  Frontend Service 
  frontend:
    build: ./../frontend
    image: flashdrivecontainerregistry2.azurecr.io/flashdrive_frontend
    ports:
      - "5000:80" # Map the exposed port 80 on the container to port 5000 on the host machine
    restart: always
    depends_on:
      - backend