# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80
#   selector:
#     app: frontend
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
# spec:
#   type: ClusterIP
#   ports:
#   - port: 8080
#   selector:
#     app: backend
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: az-flashdrive-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     #appgw.ingress.kubernetes.io/backend-hostname: "www.flashdrive-cloud.de"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /api/(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: backend
#             port:
#               number: 8080
#       - path: /(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend
#             port:
#               number: 80


apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: backend